apiVersion: apps/v1
kind: Deployment

metadata:
  name: {{ include "flask-app.fullname" . }}

spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      app: {{ include "flask-app.name" . }}

  template:
    metadata:
      labels:
        app: {{ include "flask-app.name" . }}

    spec:
      containers:
        - name: {{ include "flask-app.name" . }}

          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"

          imagePullPolicy: {{ .Values.image.pullPolicy }}

          ports:
            - containerPort: {{ .Values.containerPort }}

          env:
            - name: ENVIRONMENT
              value: "{{ .Values.env.ENVIRONMENT }}"

          envFrom:
            - configMapRef:
                name: {{ include "flask-app.fullname" . }}-config

          volumeMounts:
            - name: config-volume
              mountPath: "{{ .Values.volumeMounts.mountPath }}"

          livenessProbe:
            httpGet:
              path: "{{ .Values.livenessProbe.path }}"
              port: {{ .Values.containerPort }}

            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.livenessProbe.failureThreshold }}

          readinessProbe:
            httpGet:
              path: "{{ .Values.readinessProbe.path }}"
              port: {{ .Values.containerPort }}

            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.readinessProbe.failureThreshold }}

          resources:
{{ toYaml .Values.resources | indent 12 }}

      volumes:
        - name: config-volume
          configMap:
            name: {{ include "flask-app.fullname" . }}-config