apiVersion: v1
kind: Service

metadata:
  name: {{ include "flask-app.fullname" . }}-service

spec:
  type: {{ .Values.service.type }}

  selector:
    app: {{ include "flask-app.name" . }}

  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort }}